# -*- coding: utf-8 -*-
"""patient_routing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2YyE_BrdM7NIMevCnwSsQQzaDQag2_P
"""

from datetime import datetime

print("HI, WELCOME NEW PATIENT!")

# Patient name
name = input("What is your name? ").strip().title()
print(f"Hello {name}")

# Age calculation using current year
birth_year = input("Enter your birth year: ")
try:
    birth_year = int(birth_year)
    current_year = datetime.now().year
    age = current_year - birth_year
except ValueError:
    print("Invalid year entered. Exiting.")
    exit()

# Symptom categories (case-insensitive)
High_risk = [s.lower() for s in [
    "Allergies", "Colds and Flu", "Conjunctivitis", "Diarrhea",
    "Headaches", "Mononucleosis", "Stomach_Aches"
]]
Low_risk = [s.lower() for s in [
    "Diabetes", "Mellitus", "Hypertension", "Heart Disease",
    "Stroke", "Chronic Kidney Disease"
]]
EMT = [s.lower() for s in [
    "Heart Attack", "Stroke", "Severe Allergic Reactions",
    "Severe Burns", "Uncontrolled Seizures"
]]

hospital_name = "Mercy Saviours"
print(f"\nWelcome to {hospital_name}, {name}! You are {age} years old.")

# Symptom input
symptom_input = input("What are your symptoms? ").strip().lower()

# Patient routing based on age and symptoms
if symptom_input in EMT:
    print("EMERGENCY: Patient to be admitted to Immediate Care.")
elif symptom_input in High_risk:
    if age >= 18:
        print("Adult patient to be admitted to room #210.")
    else:
        print("Minor patient to be admitted to room #102.")
elif symptom_input in Low_risk:
    print("Patient to be admitted to general ward for monitoring.")
else:
    print("Symptom not recognized. Please consult reception for assistance.")